name: Vahan Report Automation

on:
  schedule:
    # Run daily at 9:30 AM IST (4:00 AM UTC)
    - cron: '0 4 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-vahan-automation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pandas openpyxl webdriver-manager requests
    
    - name: Install Chrome and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable xvfb
    
    - name: Set up virtual display
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &

    - name: Network diagnostics
      run: |
        echo "Testing network connectivity..."
        ping -c 3 google.com || echo "Ping failed"
        curl -I https://vahan.parivahan.gov.in/ || echo "Vahan site unreachable"
        curl -I https://parivahan.gov.in/ || echo "Parivahan site unreachable"
        echo "Network diagnostics completed"
    
    - name: Run Vahan automation
      run: |
        export DISPLAY=:99
        python vahan_automation.py
      env:
        PYTHONUNBUFFERED: 1
      
    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: vahan-reports-${{ github.run_number }}
        path: |
          *.xlsx
          *.csv
          *.json
        retention-days: 30
        
    - name: Upload logs on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: error-logs-${{ github.run_number }}
        path: |
          *.log
        retention-days: 7
